### ISSUE TITLE
Plow stops when there is no more plot to copy

### ISSUE THREAD

**Issue by Ganbin** [jlobue10/Chia_stuff#5]
I have an issue with the custom plow script.

When the source directory become empty, then I got this error:
`! 'str' object has no attribute 'parent'`

Afterwards, the new plots that are incoming are not moved anymore.

Do you have an idea where the issue might come from?

**Comment by jlobue10** [comment]
Good to know. I will have to work on this to see what is happening. For now you may need to just restart the plow.

I need to add in some error checking to properly check for this (empty source dir) and then just issue a sleep command to wait (before checking again), I think.

**Comment by Ganbin** [comment]
Thanks for the response. I will also try to do something on my side and let you know if I find something.

**Comment by jlobue10** [comment]
Sounds good. I'll happily merge a pull request if you happen to find a fix that works well. I guess I never encountered this because my plotters were faster than how quickly I could send off to the destination drives (ie. source always had plots available to move).

**Comment by Ganbin** [comment]
I think I found the issue but I need now to wait my plotter to stop and for my SSD to empty itself to make sure it works.
